# Generated by Django 4.2.6 on 2024-02-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stata',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stata',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stata',
            name='camera_name',
            field=models.CharField(max_length=100, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='stata',
            name='camera_url',
            field=models.CharField(max_length=255, verbose_name='RTSP-ссылка камеры'),
        ),
        migrations.AlterField(
            model_name='stata',
            name='face_image',
            field=models.ImageField(upload_to='face_detections/', verbose_name='Скриншот'),
        ),
        migrations.AlterField(
            model_name='stata',
            name='face_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
